[2024-08-13T11:52:19.774+0000] {processor.py:161} INFO - Started process (PID=55) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:52:19.779+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py for tasks to queue
[2024-08-13T11:52:19.781+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:52:19.781+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:52:19.785+0000] {processor.py:840} INFO - DAG(s) 'example_task_group' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:52:19.878+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:52:19.878+0000] {override.py:1858} INFO - Created Permission View: can edit on DAG:example_task_group
[2024-08-13T11:52:19.890+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:52:19.890+0000] {override.py:1858} INFO - Created Permission View: can read on DAG:example_task_group
[2024-08-13T11:52:19.893+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:52:19.893+0000] {override.py:1858} INFO - Created Permission View: can delete on DAG:example_task_group
[2024-08-13T11:52:19.896+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:52:19.896+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-08-13T11:52:19.913+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:52:19.913+0000] {dag.py:3111} INFO - Creating ORM DAG for example_task_group
[2024-08-13T11:52:19.929+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:52:19.929+0000] {dag.py:3947} INFO - Setting next_dagrun for example_task_group to 2024-08-12 00:00:00+00:00, run_after=2024-08-13 00:00:00+00:00
[2024-08-13T11:52:19.961+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py took 0.190 seconds
[2024-08-13T11:52:50.411+0000] {processor.py:161} INFO - Started process (PID=113) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:52:50.412+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py for tasks to queue
[2024-08-13T11:52:50.414+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:52:50.413+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:52:50.420+0000] {processor.py:840} INFO - DAG(s) 'example_task_group' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:52:50.435+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:52:50.435+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-08-13T11:52:50.458+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:52:50.457+0000] {dag.py:3947} INFO - Setting next_dagrun for example_task_group to 2024-08-12 00:00:00+00:00, run_after=2024-08-13 00:00:00+00:00
[2024-08-13T11:52:50.487+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py took 0.081 seconds
[2024-08-13T11:53:20.550+0000] {processor.py:161} INFO - Started process (PID=170) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:53:20.551+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py for tasks to queue
[2024-08-13T11:53:20.552+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:53:20.552+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:53:20.556+0000] {processor.py:840} INFO - DAG(s) 'example_task_group' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:53:20.569+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:53:20.569+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-08-13T11:53:20.581+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:53:20.581+0000] {dag.py:3947} INFO - Setting next_dagrun for example_task_group to 2024-08-12 00:00:00+00:00, run_after=2024-08-13 00:00:00+00:00
[2024-08-13T11:53:20.592+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py took 0.046 seconds
[2024-08-13T11:53:50.775+0000] {processor.py:161} INFO - Started process (PID=228) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:53:50.775+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py for tasks to queue
[2024-08-13T11:53:50.777+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:53:50.776+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:53:50.782+0000] {processor.py:840} INFO - DAG(s) 'example_task_group' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:53:50.798+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:53:50.798+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-08-13T11:53:50.812+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:53:50.812+0000] {dag.py:3947} INFO - Setting next_dagrun for example_task_group to 2024-08-12 00:00:00+00:00, run_after=2024-08-13 00:00:00+00:00
[2024-08-13T11:53:50.825+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py took 0.054 seconds
[2024-08-13T11:54:21.074+0000] {processor.py:161} INFO - Started process (PID=286) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:54:21.075+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py for tasks to queue
[2024-08-13T11:54:21.077+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:54:21.077+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:54:21.081+0000] {processor.py:840} INFO - DAG(s) 'example_task_group' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:54:21.094+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:54:21.094+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-08-13T11:54:21.106+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:54:21.106+0000] {dag.py:3947} INFO - Setting next_dagrun for example_task_group to 2024-08-12 00:00:00+00:00, run_after=2024-08-13 00:00:00+00:00
[2024-08-13T11:54:21.116+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py took 0.046 seconds
[2024-08-13T11:54:51.337+0000] {processor.py:161} INFO - Started process (PID=344) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:54:51.338+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py for tasks to queue
[2024-08-13T11:54:51.339+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:54:51.339+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:54:51.344+0000] {processor.py:840} INFO - DAG(s) 'example_task_group' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:54:51.359+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:54:51.359+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-08-13T11:54:51.373+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:54:51.373+0000] {dag.py:3947} INFO - Setting next_dagrun for example_task_group to 2024-08-12 00:00:00+00:00, run_after=2024-08-13 00:00:00+00:00
[2024-08-13T11:54:51.387+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py took 0.054 seconds
[2024-08-13T11:55:21.714+0000] {processor.py:161} INFO - Started process (PID=402) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:55:21.715+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py for tasks to queue
[2024-08-13T11:55:21.717+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:55:21.717+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:55:21.722+0000] {processor.py:840} INFO - DAG(s) 'example_task_group' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:55:21.736+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:55:21.735+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-08-13T11:55:21.749+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:55:21.748+0000] {dag.py:3947} INFO - Setting next_dagrun for example_task_group to 2024-08-12 00:00:00+00:00, run_after=2024-08-13 00:00:00+00:00
[2024-08-13T11:55:21.760+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py took 0.049 seconds
[2024-08-13T11:55:51.837+0000] {processor.py:161} INFO - Started process (PID=459) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:55:51.839+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py for tasks to queue
[2024-08-13T11:55:51.841+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:55:51.841+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:55:51.846+0000] {processor.py:840} INFO - DAG(s) 'example_task_group' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:55:51.865+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:55:51.865+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-08-13T11:55:51.887+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:55:51.887+0000] {dag.py:3947} INFO - Setting next_dagrun for example_task_group to 2024-08-12 00:00:00+00:00, run_after=2024-08-13 00:00:00+00:00
[2024-08-13T11:55:51.903+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py took 0.073 seconds
[2024-08-13T11:56:22.010+0000] {processor.py:161} INFO - Started process (PID=517) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:56:22.010+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py for tasks to queue
[2024-08-13T11:56:22.012+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:56:22.012+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:56:22.018+0000] {processor.py:840} INFO - DAG(s) 'example_task_group' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:56:22.033+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:56:22.033+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-08-13T11:56:22.049+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:56:22.049+0000] {dag.py:3947} INFO - Setting next_dagrun for example_task_group to 2024-08-12 00:00:00+00:00, run_after=2024-08-13 00:00:00+00:00
[2024-08-13T11:56:22.060+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py took 0.054 seconds
[2024-08-13T11:56:52.418+0000] {processor.py:161} INFO - Started process (PID=575) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:56:52.424+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py for tasks to queue
[2024-08-13T11:56:52.425+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:56:52.425+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:56:52.431+0000] {processor.py:840} INFO - DAG(s) 'example_task_group' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_task_group.py
[2024-08-13T11:56:52.458+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:56:52.456+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-08-13T11:56:53.029+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:56:53.029+0000] {process_utils.py:263} INFO - Waiting up to 5 seconds for processes to exit...
[2024-08-13T11:56:53.046+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:56:53.046+0000] {process_utils.py:263} INFO - Waiting up to 5 seconds for processes to exit...
[2024-08-13T11:56:53.062+0000] {logging_mixin.py:188} INFO - [2024-08-13T11:56:53.061+0000] {base.py:264} ERROR - Exception closing connection <connection object at 0xf9379b5a3ec0; dsn: 'user=airflow password=xxx dbname=airflow host=postgres', closed: 1>
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2138, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.12/encodings/utf_8.py", line 15, in decode
    def decode(input, errors='strict'):
    
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/manager.py", line 457, in _exit_gracefully
    sys.exit(os.EX_OK)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 260, in _close_connection
    self._dialect.do_terminate(connection)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 692, in do_close
    dbapi_connection.close()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/manager.py", line 457, in _exit_gracefully
    sys.exit(os.EX_OK)
SystemExit: 0
[2024-08-13T11:56:53.067+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2138, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.12/encodings/utf_8.py", line 15, in decode
    def decode(input, errors='strict'):
    
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/manager.py", line 457, in _exit_gracefully
    sys.exit(os.EX_OK)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 38, in create_session
    yield session
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 895, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 664, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 680, in _sync_to_db
    DAG.bulk_write_to_db(dags.values(), processor_subdir=processor_subdir, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 3101, in bulk_write_to_db
    orm_dags: list[DagModel] = session.scalars(query).unique().all()
                               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1778, in scalars
    return self.execute(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2148, in _handle_dbapi_exception
    self.invalidate(e)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 749, in invalidate
    self._dbapi_connection.invalidate(exception)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1121, in invalidate
    self._connection_record.invalidate(e=e, soft=soft)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 610, in invalidate
    self.__close(terminate=True)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 673, in __close
    self.__pool._close_connection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 260, in _close_connection
    self._dialect.do_terminate(connection)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 692, in do_close
    dbapi_connection.close()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/manager.py", line 457, in _exit_gracefully
    sys.exit(os.EX_OK)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1062, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 683, in do_rollback
    dbapi_connection.rollback()
psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 859, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 78, in wrapper
    with create_session() as session:
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 44, in create_session
    session.close()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1816, in close
    self._close_impl(invalidate=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1858, in _close_impl
    transaction.close(invalidate)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 926, in close
    transaction.close()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2426, in close
    self._do_close()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2649, in _do_close
    self._close_impl()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2635, in _close_impl
    self._connection_rollback_impl()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2627, in _connection_rollback_impl
    self.connection._rollback_impl()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1064, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1062, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlalchemy.exc.InterfaceError: (psycopg2.InterfaceError) connection already closed
(Background on this error at: https://sqlalche.me/e/14/rvf5)
